version: "3.6"
services:
  postgres:
    image: postgres:12
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: PostsgresQLPassword
      POSTGRES_DB: DatabaseName
    networks:
      - hasura

  graphql-engine:
    image: hasura/graphql-engine:v1.3.2
    depends_on:
      - "postgres"
    environment:
      HASURA_GRAPHQL_DATABASE_URL: postgres://postgres:PostsgresQLPassword@postgres:5432/DatabaseName
      HASURA_GRAPHQL_ENABLE_CONSOLE: "true"
      HASURA_GRAPHQL_CORS_DOMAIN: "https://hasura.pg.distillery.com, http://localhost:4200"
      HASURA_GRAPHQL_ADMIN_SECRET: YourVerySecureSecret
      HASURA_GRAPHQL_UNAUTHORIZED_ROLE: anonymous
      HASURA_GRAPHQL_JWT_SECRET: '{"type":"RS256", "jwk_url": "https://www.googleapis.com/service_accounts/v1/jwk/securetoken@system.gserviceaccount.com", "audience": "<firebase-project-id>", "issuer": "https://securetoken.google.com/<firebase-project-id>"}'
    networks:
      - traefik
      - hasura
    deploy:
      labels:
        - "traefik.enable=true"
        - "traefik.port=8080"
        - "traefik.frontend.rule=Host:hasura.pg.distillery.com;PathPrefixStrip:/api"

volumes:
  db_data:

networks:
  hasura:
    driver: overlay
  traefik:
    driver: overlay
    external: true
